[DEFAULT]
LoggingLevel = WARNING
PLOT_DISTR = False
PLOT_DDTW = False

[LSHA PARAMETERS]
; either 'S' (strict) or 'W' (weak): strict overapproximates, weak potentially results in non-determinism
EQ_CONDITION = w
; no need to perform the MI query when there is only one candidate flow condition (e.g., the constant function)
; in that case, set to ACTIVATE_MI_QUERY False
ACTIVATE_MI_QUERY = False
; set ACTIVATE_HT_QUERY to False if you wish to de-activate the HT query for some reason
ACTIVATE_HT_QUERY = True
; if the HT query is active, it can either be "deterministic" or "stochastic"
; HT_QUERY_TYPE = D -> deterministic (compares observations with fixed values)
; HT_QUERY_TYPE = S -> stochastic (identifies distributions)
HT_QUERY_TYPE = D
; The higher the more samples are collected at each ref query (more robust, but takes more time)
N_min = 1
; Amplitude of the noise that is added when performing data augmentation (needed in case of scarce observations).
; NOT NEEDED WHEN RESAMPLE STRATEGY==UPPAAL (e.g., the THERMO use case).
DELTA = 0.0

[TRACE GENERATION]
UPPAAL_PATH = /Applications/Dev/uppaal-bin/bin
UPPAAL_SCRIPT_PATH = /resources/scripts/verify.sh
UPPAAL_MODEL_PATH = /resources/uppaal_resources/thermostat.xml
UPPAAL_QUERY_PATH = /resources/uppaal_resources/thermostat.q
UPPAAL_OUT_PATH = /resources/upp_results/{}.txt

SIM_LOGS_PATH = /resources/traces/

[SUL CONFIGURATION]
CASE_STUDY = LEGO_FACTORY
; resample strategy is either:
; UPPAAL (asks UPPAAL for new traces)
; SIM (uses pre-collected traces from SIM_LOGS_PATH)
; SKG (queries an SKG for data)
; XES (uses .xes log files)
RESAMPLE_STRATEGY = XES
CS_VERSION = 1
SHA_SAVE_PATH = {}/resources/learned_sha/
REPORT_SAVE_PATH = {}/resources/learned_sha/

[AUTO-TWIN CONFIGURATION]
; item/resource/plant
POV = item
; START_T = 0
; END_T = 10000000
START_DATE = 2025-09-05-12-30-00
END_DATE = 2025-09-05-12-34-30
